FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json tsconfig.json ./
RUN npm install

COPY firebase-key.json ./

COPY src ./src

RUN npx tsc

FROM node:20-alpine AS runtime

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /app/dist ./dist

COPY firebase-key.json ./

EXPOSE 3000

CMD ["node", "dist/server.js"]